### ISSUE TITLE
Usage Example would be useful

### ISSUE THREAD

**Issue by andym2009** [ttyridal/phpdlna#1]
Hi,

As far as I can tell the php runs ok, but I am struggling to figure out exactly how to use it.

An example would be great, including how to use the debug/logging.

Looks like it could be very useful.

I coded php many years ago, but am only now returning to it, so I am a bit rusty to say the least.

Many thanks

Andy

**Comment by ttyridal** [comment]
Hi,

I've tried to improve the readme a tiny bit.  The log is nothing special. As long as /tmp is writeable for the webserver, you'll get whatever is written with _debug into a `phpdlna-debug.txt` file there.

I've also started to write a small tools/validate.py that can be used for troubleshooting or checking at everything is "supposed to work" (lot's of if's etc here.. the DLNA players can be terrible picky, and no twos are alike.)
