### ISSUE TITLE
Doesn't work with PlugPlayer iOS app nor Kodi

### ISSUE THREAD

**Issue by avibrazil** [ttyridal/phpdlna#2]
I configured a server on http://dlna.digitalk7.com/phpdlna/rootDesc.xml but it doesn't work. I get strange error messages. I also tried to configure Kodi with this URL but I'm not sure how to do it, never used Kodi as a renderer for such a remote server.

I'm not using the UDP broadcast, I'm simply putting the URL on my UPnP client, which is a procedure that works with other remote-non-broadcast servers.

Is there any debug messages I can send you to help me fix this ?

Thank you in advance

**Comment by ttyridal** [comment]
Hi, the logs would need to come from the renderer as I expect you'll only
see a request for rootdesc.xml on your server. You could try the alternate
(non dlna) rootdesc.

And I'd try to remove 'mus/' from your baseurl too

Cheers T

**Comment by ttyridal** [comment]
hi, did my suggestions help?
