### ISSUE TITLE
spaces in urls - rawurlencode ?

### ISSUE THREAD

**Issue by netspoon** [ttyridal/phpdlna#4]
From the apache logs I can see some clients requesting a truncated URL where there are spaces in the path (resulting in a error), and testing with VLC logs failures for all paths containing spaces (without actually making a server request).

Quick fix seems to be to rawurlencode the path as it assembled in lookup_real_path, and in BrowseDirectChildren which replaces the spaces with %20 and seems to fix the VLC issue.

**Comment by ttyridal** [comment]
ouch.. someone's not been following up on the issue reports 😔

fixed by @Tuckbros in #5
