### ISSUE TITLE
Truncated folder name

### ISSUE THREAD

**Issue by Tuckbros** [ttyridal/phpdlna#6]
I have a folders names which appear to be truncated when displayed in the list. Whatever they can be properly opened and content is accessible.
It seems to happen with folder name with a like `[ mydomain.com ] my wonderfull folder` because of the point in the square bracket. With such a name the folder appear as `[ mydomain`

**Comment by Tuckbros** [comment]
According to my tests, solved by pull requests #7 (removing extension only on files and not on folders)  and #8 (adding a rawurlencode)

**Comment by ttyridal** [comment]
That's perfect. both accepted!  Thanks for your contribution
